/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceChatRouteImport } from './routes/voice-chat'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminRagDocumentsIndexRouteImport } from './routes/admin/rag-documents/index'
import { Route as AdminAccountsIndexRouteImport } from './routes/admin/accounts/index'
import { Route as AdminAccountsRolesRouteImport } from './routes/admin/accounts/roles'

const VoiceChatRoute = VoiceChatRouteImport.update({
  id: '/voice-chat',
  path: '/voice-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRagDocumentsIndexRoute = AdminRagDocumentsIndexRouteImport.update({
  id: '/admin/rag-documents/',
  path: '/admin/rag-documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsIndexRoute = AdminAccountsIndexRouteImport.update({
  id: '/admin/accounts/',
  path: '/admin/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRolesRoute = AdminAccountsRolesRouteImport.update({
  id: '/admin/accounts/roles',
  path: '/admin/accounts/roles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/voice-chat': typeof VoiceChatRoute
  '/admin/logs': typeof AdminLogsRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/accounts/roles': typeof AdminAccountsRolesRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
  '/admin/rag-documents': typeof AdminRagDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/voice-chat': typeof VoiceChatRoute
  '/admin/logs': typeof AdminLogsRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/accounts/roles': typeof AdminAccountsRolesRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
  '/admin/rag-documents': typeof AdminRagDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/voice-chat': typeof VoiceChatRoute
  '/admin/logs': typeof AdminLogsRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/accounts/roles': typeof AdminAccountsRolesRoute
  '/admin/accounts/': typeof AdminAccountsIndexRoute
  '/admin/rag-documents/': typeof AdminRagDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat'
    | '/voice-chat'
    | '/admin/logs'
    | '/auth/login'
    | '/admin'
    | '/admin/accounts/roles'
    | '/admin/accounts'
    | '/admin/rag-documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/voice-chat'
    | '/admin/logs'
    | '/auth/login'
    | '/admin'
    | '/admin/accounts/roles'
    | '/admin/accounts'
    | '/admin/rag-documents'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat'
    | '/voice-chat'
    | '/admin/logs'
    | '/auth/login'
    | '/admin/'
    | '/admin/accounts/roles'
    | '/admin/accounts/'
    | '/admin/rag-documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  VoiceChatRoute: typeof VoiceChatRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAccountsRolesRoute: typeof AdminAccountsRolesRoute
  AdminAccountsIndexRoute: typeof AdminAccountsIndexRoute
  AdminRagDocumentsIndexRoute: typeof AdminRagDocumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-chat': {
      id: '/voice-chat'
      path: '/voice-chat'
      fullPath: '/voice-chat'
      preLoaderRoute: typeof VoiceChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rag-documents/': {
      id: '/admin/rag-documents/'
      path: '/admin/rag-documents'
      fullPath: '/admin/rag-documents'
      preLoaderRoute: typeof AdminRagDocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/': {
      id: '/admin/accounts/'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/roles': {
      id: '/admin/accounts/roles'
      path: '/admin/accounts/roles'
      fullPath: '/admin/accounts/roles'
      preLoaderRoute: typeof AdminAccountsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  VoiceChatRoute: VoiceChatRoute,
  AdminLogsRoute: AdminLogsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAccountsRolesRoute: AdminAccountsRolesRoute,
  AdminAccountsIndexRoute: AdminAccountsIndexRoute,
  AdminRagDocumentsIndexRoute: AdminRagDocumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
