/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceChatRouteImport } from './routes/voice-chat'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminWorkflowsIndexRouteImport } from './routes/admin/workflows/index'
import { Route as AdminRagDocumentsIndexRouteImport } from './routes/admin/rag-documents/index'
import { Route as AdminMcpServersIndexRouteImport } from './routes/admin/mcp-servers/index'
import { Route as AdminLogsIndexRouteImport } from './routes/admin/logs/index'
import { Route as AdminAccountsIndexRouteImport } from './ro./routes/admin/accounts/index
import { Route as AdminAccountsRolesRouteImport } from './ro./routes/admin/accounts/roles

const VoiceChatRoute = VoiceChatRouteImport.update({
  id: '/voice-chat',
  path: '/voice-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowsIndexRoute = AdminWorkflowsIndexRouteImport.update({
  id: '/admin/workflows/',
  path: '/admin/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRagDocumentsIndexRoute = AdminRagDocumentsIndexRouteImport.update({
  id: '/admin/rag-documents/',
  path: '/admin/rag-documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMcpServersIndexRoute = AdminMcpServersIndexRouteImport.update({
  id: '/admin/mcp-servers/',
  path: '/admin/mcp-servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsIndexRoute = AdminLogsIndexRouteImport.update({
  id: '/admin/logs/',
  path: '/admin/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsIndexRoute = AdminAccountsIndexRouteImport.update({
  id: '/admin/accounts/',
  path: '/admin/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRolesRoute = AdminAccountsRolesRouteImport.update({
  id: '/admin/accounts/roles',
  path: '/admin/accounts/roles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/voice-chat': typeof VoiceChatRoute
  '/admin/config': typeof AdminConfigRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/admin': typeof AdminIndexRoute
  '/admin/accounts/roles': typeof AdminAccountsRolesRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
  '/admin/logs': typeof AdminLogsIndexRoute
  '/admin/mcp-servers': typeof AdminMcpServersIndexRoute
  '/admin/rag-documents': typeof AdminRagDocumentsIndexRoute
  '/admin/workflows': typeof AdminWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/voice-chat': typeof VoiceChatRoute
  '/admin/config': typeof AdminConfigRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/admin': typeof AdminIndexRoute
  '/admin/accounts/roles': typeof AdminAccountsRolesRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
  '/admin/logs': typeof AdminLogsIndexRoute
  '/admin/mcp-servers': typeof AdminMcpServersIndexRoute
  '/admin/rag-documents': typeof AdminRagDocumentsIndexRoute
  '/admin/workflows': typeof AdminWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/voice-chat': typeof VoiceChatRoute
  '/admin/config': typeof AdminConfigRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/accounts/roles': typeof AdminAccountsRolesRoute
  '/admin/accounts/': typeof AdminAccountsIndexRoute
  '/admin/logs/': typeof AdminLogsIndexRoute
  '/admin/mcp-servers/': typeof AdminMcpServersIndexRoute
  '/admin/rag-documents/': typeof AdminRagDocumentsIndexRoute
  '/admin/workflows/': typeof AdminWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/about'
  | '/chat'
  | '/voice-chat'
  | '/admin/config'
  | '/auth/login'
  | '/auth/logout'
  | '/admin'
  | '/admin/accounts/roles'
  | '/admin/accounts'
  | '/admin/logs'
  | '/admin/mcp-servers'
  | '/admin/rag-documents'
  | '/admin/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
  | '/'
  | '/about'
  | '/chat'
  | '/voice-chat'
  | '/admin/config'
  | '/auth/login'
  | '/auth/logout'
  | '/admin'
  | '/admin/accounts/roles'
  | '/admin/accounts'
  | '/admin/logs'
  | '/admin/mcp-servers'
  | '/admin/rag-documents'
  | '/admin/workflows'
  id:
  | '__root__'
  | '/'
  | '/about'
  | '/chat'
  | '/voice-chat'
  | '/admin/config'
  | '/auth/login'
  | '/auth/logout'
  | '/admin/'
  | '/admin/accounts/roles'
  | '/admin/accounts/'
  | '/admin/logs/'
  | '/admin/mcp-servers/'
  | '/admin/rag-documents/'
  | '/admin/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  VoiceChatRoute: typeof VoiceChatRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAccountsRolesRoute: typeof AdminAccountsRolesRoute
  AdminAccountsIndexRoute: typeof AdminAccountsIndexRoute
  AdminLogsIndexRoute: typeof AdminLogsIndexRoute
  AdminMcpServersIndexRoute: typeof AdminMcpServersIndexRoute
  AdminRagDocumentsIndexRoute: typeof AdminRagDocumentsIndexRoute
  AdminWorkflowsIndexRoute: typeof AdminWorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-chat': {
      id: '/voice-chat'
      path: '/voice-chat'
      fullPath: '/voice-chat'
      preLoaderRoute: typeof VoiceChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflows/': {
      id: '/admin/workflows/'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AdminWorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rag-documents/': {
      id: '/admin/rag-documents/'
      path: '/admin/rag-documents'
      fullPath: '/admin/rag-documents'
      preLoaderRoute: typeof AdminRagDocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mcp-servers/': {
      id: '/admin/mcp-servers/'
      path: '/admin/mcp-servers'
      fullPath: '/admin/mcp-servers'
      preLoaderRoute: typeof AdminMcpServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs/': {
      id: '/admin/logs/'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/': {
      id: '/admin/accounts/'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/roles': {
      id: '/admin/accounts/roles'
      path: '/admin/accounts/roles'
      fullPath: '/admin/accounts/roles'
      preLoaderRoute: typeof AdminAccountsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  VoiceChatRoute: VoiceChatRoute,
  AdminConfigRoute: AdminConfigRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAccountsRolesRoute: AdminAccountsRolesRoute,
  AdminAccountsIndexRoute: AdminAccountsIndexRoute,
  AdminLogsIndexRoute: AdminLogsIndexRoute,
  AdminMcpServersIndexRoute: AdminMcpServersIndexRoute,
  AdminRagDocumentsIndexRoute: AdminRagDocumentsIndexRoute,
  AdminWorkflowsIndexRoute: AdminWorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
