networks:
  pumai-net:

services:
  mariadb: # Added MariaDB service
    image: mariadb:latest
    container_name: pumai-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_database_name
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - pumai-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pumai-app
    depends_on:
      - mongoinit
      - qdrant
      - mongo
      - redis
    environment:
      - NODE_ENV=production
    volumes:
      - ./server/.env.prod:/app/server/.env.prod
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: ["sh", "-c", "sleep 5 && npm run start"]
    networks:
      - pumai-net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: pumai-qdrant
    depends_on:
      - mongo
    volumes:
      - qdrant-data:/data
    restart: unless-stopped
    ports: # Just for development, remove in production
      - "6333:6333"
    networks:
      - pumai-net

  redis:
    image: redis:7-alpine
    container_name: pumai-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports: # Just for development, remove in production
      - "6379:6379"
    networks:
      - pumai-net

volumes:
  mongo-data:
  qdrant-data:
  redis-data:
  mariadb-data:
