services:
  mongo:
    image: mongo:latest
    container_name: pumai-db
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    restart: unless-stopped

  mongoinit:
    image: mongo:latest
    depends_on:
      - mongo
    entrypoint: ["bash", "-c"]
    command: >
      "
      echo 'Waiting for MongoDB to be ready...' &&
      until mongo --host mongo --eval 'db.adminCommand(\"ping\")' >/dev/null 2>&1; do
        sleep 1;
      done &&
      echo 'Mongo is up. Initiating replica set...' &&
      mongo --host mongo --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [{ _id: 0, host: \"mongo:27017\" }]
        });
      '
      "
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pumai-app
    depends_on:
      - mongoinit
      - qdrant
      - mongo
      - redis
    environment:
      - NODE_ENV=production
    volumes:
      - ./server/.env.prod:/app/server/.env.prod
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: ["sh", "-c", "sleep 5 && npm run start"]

  qdrant:
    image: qdrant/qdrant:latest
    container_name: pumai-qdrant
    depends_on:
      - mongo
    volumes:
      - qdrant-data:/data
    restart: unless-stopped
    ports: # Just for development, remove in production
      - "6333:6333"

  redis:
    image: redis:7-alpine
    container_name: pumai-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports: # Just for development, remove in production
      - "6379:6379"

volumes:
  mongo-data:
  qdrant-data:
  redis-data:
