export type WorkflowName = string;

//#region Registry
export type WorkflowRequestBody = {
  intent: "get-info" | "execute-step";
  currentStep?: string;
  userInput?: string;
};

export type WorkflowStepResult = {
  replies: {
    type: "text" | "image" | "url" | "system" | "error";
    content: string;
  }[];
  nextStep: string | null; // null = workflow ends
  recommendedReplies: string[]; // These will be shown as suggestions for the user to click on after the step is executed, to continue the workflow. They can be generated by the LLM or be static options defined in the workflow step handler.
};

export interface WorkflowRegistryInfo {
  name: WorkflowName;
  description: string;
  firstStep: string;
  steps: string[];
}
//#endregion

//#region Sessions
export type WorkflowSession = {
  sessionId: string;
  userId: string;
  activeWorkflow: WorkflowName;
  currentStep: string;
  data: Record<string, any>; // This can hold any data that the workflow steps want to persist across the session
  startedAt: Date;
};
//#endregion
